/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorMenuRouteImport } from './routes/vendor.menu'
import { Route as VendorHistoryRouteImport } from './routes/vendor.history'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as RRestaurantIdRouteImport } from './routes/r.$restaurantId'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminMealsRouteImport } from './routes/admin.meals'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as TrackGCodeRouteImport } from './routes/track.g.$code'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorMenuRoute = VendorMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => VendorRoute,
} as any)
const VendorHistoryRoute = VendorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VendorRoute,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackRoute,
} as any)
const RRestaurantIdRoute = RRestaurantIdRouteImport.update({
  id: '/r/$restaurantId',
  path: '/r/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMealsRoute = AdminMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const TrackGCodeRoute = TrackGCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => TrackRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/r/$restaurantId': typeof RRestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/track/': typeof TrackIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/track/g/$code': typeof TrackGCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/r/$restaurantId': typeof RRestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/track': typeof TrackIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/track/g/$code': typeof TrackGCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/r/$restaurantId': typeof RRestaurantIdRoute
  '/track/$id': typeof TrackIdRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/track/': typeof TrackIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/track/g/$code': typeof TrackGCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/rider'
    | '/search'
    | '/support'
    | '/track'
    | '/vendor'
    | '/admin/dispatch'
    | '/admin/meals'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/riders'
    | '/admin/vendors'
    | '/r/$restaurantId'
    | '/track/$id'
    | '/vendor/history'
    | '/vendor/menu'
    | '/vendor/orders'
    | '/admin/'
    | '/orders/'
    | '/track/'
    | '/vendor/'
    | '/orders/$id'
    | '/track/g/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/rider'
    | '/search'
    | '/support'
    | '/admin/dispatch'
    | '/admin/meals'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/riders'
    | '/admin/vendors'
    | '/r/$restaurantId'
    | '/track/$id'
    | '/vendor/history'
    | '/vendor/menu'
    | '/vendor/orders'
    | '/admin'
    | '/orders'
    | '/track'
    | '/vendor'
    | '/orders/$id'
    | '/track/g/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/rider'
    | '/search'
    | '/support'
    | '/track'
    | '/vendor'
    | '/admin/dispatch'
    | '/admin/meals'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/riders'
    | '/admin/vendors'
    | '/r/$restaurantId'
    | '/track/$id'
    | '/vendor/history'
    | '/vendor/menu'
    | '/vendor/orders'
    | '/admin/'
    | '/orders/'
    | '/track/'
    | '/vendor/'
    | '/_authenticated/orders/$id'
    | '/track/g/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RiderRoute: typeof RiderRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TrackRoute: typeof TrackRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  RRestaurantIdRoute: typeof RRestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/track/': {
      id: '/track/'
      path: '/'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof TrackRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/menu': {
      id: '/vendor/menu'
      path: '/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof VendorMenuRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/history': {
      id: '/vendor/history'
      path: '/history'
      fullPath: '/vendor/history'
      preLoaderRoute: typeof VendorHistoryRouteImport
      parentRoute: typeof VendorRoute
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/r/$restaurantId': {
      id: '/r/$restaurantId'
      path: '/r/$restaurantId'
      fullPath: '/r/$restaurantId'
      preLoaderRoute: typeof RRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meals': {
      id: '/admin/meals'
      path: '/meals'
      fullPath: '/admin/meals'
      preLoaderRoute: typeof AdminMealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/g/$code': {
      id: '/track/g/$code'
      path: '/g/$code'
      fullPath: '/track/g/$code'
      preLoaderRoute: typeof TrackGCodeRouteImport
      parentRoute: typeof TrackRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminMealsRoute: typeof AdminMealsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDispatchRoute: AdminDispatchRoute,
  AdminMealsRoute: AdminMealsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface TrackRouteChildren {
  TrackIdRoute: typeof TrackIdRoute
  TrackIndexRoute: typeof TrackIndexRoute
  TrackGCodeRoute: typeof TrackGCodeRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackIdRoute: TrackIdRoute,
  TrackIndexRoute: TrackIndexRoute,
  TrackGCodeRoute: TrackGCodeRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

interface VendorRouteChildren {
  VendorHistoryRoute: typeof VendorHistoryRoute
  VendorMenuRoute: typeof VendorMenuRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorHistoryRoute: VendorHistoryRoute,
  VendorMenuRoute: VendorMenuRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RiderRoute: RiderRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TrackRoute: TrackRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  RRestaurantIdRoute: RRestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
